export { default as Welcome } from './WelcomePage';
export { default as Register } from './RegisterPage';
export { default as Login } from './LoginPage';
export { default as Main } from './MainPage';
export { default as DetailCard } from './DetailCardPage';
export { default as Profile } from './ProfilePage';
export { default as AddAccountGetInfo } from './AddAccountGetInfoPage';
export { default as AddAccountSetCard } from './AddAccountSetCardPage';
export { default as EstablishAccountPassword } from './EstablishAccountPasswordPage';
